--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- OIRAT
--========================================================================================================================
		("LOC_CIVILIZATION_ANT_OIRAT_NAME",  
		"Oirat"	),
		("LOC_CIVILIZATION_ANT_OIRAT_DESCRIPTION",  
		"Oirat Empire"	),
		("LOC_CIVILIZATION_ANT_OIRAT_ADJECTIVE",  
		"Oirat"	),	
--------------------------------------------------------------------
-- UA
--------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_ANT_DORBEN_OIRAD_NAME",  
		"Dorben Oirad"	),
		("LOC_TRAIT_CIVILIZATION_ANT_DORBEN_OIRAD_DESCRIPTION",  
		"Cities receive +1 [ICON_GOLD] Gold, +1 [ICON_PRODUCTION] Production from every other city you control within 6 tiles. Receive a sum of [ICON_GOLD] Gold and [ICON_CULTURE] Culture from settling and conquering cities."),
		("LOC_GOODYHUT_LARGE_CULTURE_DESCRIPTION",  
		"[COLOR_FLOAT_CULTURE]+{1_Value} [ICON_CULTURE]"),
--------------------------------------------------------------------
-- Cities
--------------------------------------------------------------------
		("LOC_CITY_NAME_ANT_OIRAT_GHULJA",
		"Ghulja"),
		("LOC_CITY_NAME_ANT_OIRAT_ELISTA",
		"Elista"),
		("LOC_CITY_NAME_ANT_OIRAT_URUMQI",
		"Urumqi"),
		("LOC_CITY_NAME_ANT_OIRAT_BASHANTA",
		"Bashanta"),
		("LOC_CITY_NAME_ANT_OIRAT_TURPAN",
		"Turpan"),
		("LOC_CITY_NAME_ANT_OIRAT_LAGAN",
		"Lagan"),
		("LOC_CITY_NAME_ANT_OIRAT_TARBAGATAI",
		"Tarbagatai"),
		("LOC_CITY_NAME_ANT_OIRAT_KASHGAR",
		"Kashgar"),
		("LOC_CITY_NAME_ANT_OIRAT_KUBAKSERAI",
		"Kubakserai"),
		("LOC_CITY_NAME_ANT_OIRAT_KHOVD",
		"Khovd"),
		("LOC_CITY_NAME_ANT_OIRAT_MARALBEXI",
		"Maralbexi"),
		("LOC_CITY_NAME_ANT_OIRAT_ALTAI",
		"Altai"),
		("LOC_CITY_NAME_ANT_OIRAT_ULAANGOM",
		"Ulaangom"),
		("LOC_CITY_NAME_ANT_OIRAT_USU",
		"Usu"),
		("LOC_CITY_NAME_ANT_OIRAT_KARAMAY",
		"Karamay"),
		("LOC_CITY_NAME_ANT_OIRAT_KARKARALY",
		"Karkaraly"),
		("LOC_CITY_NAME_ANT_OIRAT_AKSU",
		"Aksu"),
		("LOC_CITY_NAME_ANT_OIRAT_YARKAND",
		"Yarkand"),
		("LOC_CITY_NAME_ANT_OIRAT_HOTAN",
		"Hotan"),
		("LOC_CITY_NAME_ANT_OIRAT_YENGISAR",
		"Yengisar"),
		("LOC_CITY_NAME_ANT_OIRAT_KARGILIK",
		"Kargilik"),
		("LOC_CITY_NAME_ANT_OIRAT_HAMI",
		"Hami"),
		("LOC_CITY_NAME_ANT_OIRAT_UCH_TURPAN",
		"Uch Turpan"),
		("LOC_CITY_NAME_ANT_OIRAT_HUIYUAN",
		"Huiyuan"),
		("LOC_CITY_NAME_ANT_OIRAT_TARAZ",
		"Taraz"),
		("LOC_CITY_NAME_ANT_OIRAT_TASHKENT",
		"Tashkent"),
		("LOC_CITY_NAME_ANT_OIRAT_SAYRAM",
		"Sayram"),
		("LOC_CITY_NAME_ANT_OIRAT_HOXTOLGAY",
		"Hoxtolgay"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_ANT_OIRAT_MALE_1",
		"Dzhirgan"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_2",
		"Ulan"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_3",
		"Ayuka"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_4",
		"Bata"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_5",
		"Tzatyr"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_6",
		"Altn"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_7",
		"Chon"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_8",
		"Bembö"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_9",
		"Tavn"),
		("LOC_CITIZEN_ANT_OIRAT_MALE_10",
		"Mergen"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_1",
		"Dzhirgana"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_2",
		"Söökhlö"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_3",
		"Duya"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_4",
		"Elistina"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_5",
		"Kermesh"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_6",
		"Tzetzgö"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_7",
		"Bayr"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_8",
		"Chona"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_9",
		"Buinta"),
		("LOC_CITIZEN_ANT_OIRAT_FEMALE_10",
		"Altna"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_MALE_1",
		"Kirsän"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_MALE_2",
		"Ijl"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_MALE_3",
		"Mikula"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_MALE_4",
		"Adyan"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_MALE_5",
		"Vazki"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_FEMALE_1",
		"Dunge"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_FEMALE_2",
		"Tzerena"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_FEMALE_3",
		"Tzatana"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_FEMALE_4",
		"Notana"),
		("LOC_CITIZEN_ANT_OIRAT_MODERN_FEMALE_5",
		"Bayra"),
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_ANT_OIRAT_LOCATION",
		"Asia"),
		("LOC_CIVINFO_ANT_OIRAT_SIZE",
		"Modern Kalmykia: Est. 29.4 thousand square miles (76.1 thousand square km)"),
		("LOC_CIVINFO_ANT_OIRAT_POPULATION",
		"638,372 (2013 est.)"),
		("LOC_CIVINFO_ANT_OIRAT_CAPITAL",
		"Ghulja (Dzungar Khanate capital)"),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ANT_OIRAT_CHAPTER_HISTORY_PARA_1",
		"Although the Oirats originated in the eastern parts of Central Asia, the most prominent group today is located in Kalmykia, a federal subject of Russia, where they are called Kalmyks."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ANT_OIRAT_CHAPTER_HISTORY_PARA_2",
		"The name Oirat may derive from a corruption of the group's original name Dorben Oirad, meaning The Allied Four. Perhaps inspired by the designation Dorben Oirad, other Mongols at times used the term Döchin Mongols for themselves, but there was rarely as great a degree of unity among larger numbers of tribes as among the Oirats."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ANT_OIRAT_CHAPTER_HISTORY_PARA_3",
		"The Oirats share some history, geography, culture and language with the Eastern Mongols, and were at various times united under the same leader as a larger Mongol entity - whether that ruler was of Oirat descent or of Chingissids. After the fall of the Yuan dynasty, Oirat and Eastern Mongols had developed separate identities to the point where Oirats called themselves Four Oirats while they only called those under the Khagans in the east as Mongols."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ANT_OIRAT_CHAPTER_HISTORY_PARA_4",
		"One of the earliest mentions of the Oirat people in a historical text can be found in The Secret History of the Mongols, the 13th century chronicle of Genghis Khan's rise to power. Subject to the khan Oirats would form themselves as a loyal and formidable faction of the Mongol war machine."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ANT_OIRAT_CHAPTER_HISTORY_PARA_5",
		"In 1295, more than 10,000 Oirats under Targhai Khurgen fled Syria, then under the Mamluks because they were despised by both Muslim Mongols and local Turks. Due to the fact that the Oirats were near both the Chagatai Khanate and the Golden Horde, they had strong ties with them and many Mongol khans had Oirat wives."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ANT_OIRAT_CHAPTER_HISTORY_PARA_6",
		"A non-Genghisids alliance was formed by the Four Oirats, made out of the Keraites, Naiman, Barghud, and old Oirats. The Borjigid Khans were displaced from power by the Oirats with Ming help and only ruled as puppet khans until the Ming and Oirats ended the alliance when the Yongle Emperor launched a campaign against them."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ANT_OIRAT_CHAPTER_HISTORY_PARA_7",
		"The greatest ruler of the Four Oirats was Esen Tayisi who led the Four Oirats from 1438 to 1454, during which time he unified Mongolia under his puppet khan Toghtoa Bukha. From the 14th until the middle of the 18th century, the Oirats were often at war with the Eastern Mongols and also few times reunited with the Eastern Mongols during the rule of Dayan Khan and Tümen Zasagt Khan."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_ANT_OIRAT_CHAPTER_HISTORY_PARA_8",
		"There were 600,000 Khalkha Mongols and 600,000 Oirats in 1755 and now 2,3 million Khalkha and 638,372 Oirats live in four counties while a few hundred Choros people live in Mongolia. The Oirat's state had a small army and 200 Kalmyk soldiers defeated 1,700 Soviet soldiers in Durvud province of Kalmykia but the Oirat's state destroyed by the Soviet Army in 1930."),
--------------------------------------------------------------------
-- RWF Support
--------------------------------------------------------------------
		("LOC_CIVILIZATION_ANT_OIRAT_DESCRIPTION_JFD_CIVILIZATION",  
		"Oirat Civilization"	),
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_ANT_OIRAT",  
		"Taishi"	),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_ANT_OIRAT",  
		"Noyan"	),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_ANT_OIRAT",  
		"Khan"	),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_ANT_OIRAT",  
		"Taishi"	),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_ANT_OIRAT",  
		"Khong Tayiji"	),
		("LOC_GOVERNMENT_JFD_ABS_MONARCHY_LEADER_TITLE_ANT_OIRAT",  
		"Khan"	),
		("LOC_GOVERNMENT_JFD_CONS_MONARCHY_LEADER_TITLE_ANT_OIRAT",  
		"Khong Tayiji"	),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_ANT_OIRAT",  
		"Taishi"	),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_ANT_OIRAT",  
		"Khan"	),
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_ANT_OIRAT",  
		"Khagan"	),
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Taishi"	),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Noyan"	),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Khatun"	),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Gonji"	),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Behi"	),
		("LOC_GOVERNMENT_JFD_ABS_MONARCHY_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Khatun"	),
		("LOC_GOVERNMENT_JFD_CONS_MONARCHY_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Gonji"	),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Behi"	),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Khatun"	),
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_ANT_OIRAT_FEMININE",  
		"Khatun"	),
--========================================================================================================================
-- ULAN ZALATA
--========================================================================================================================
		("LOC_UNIT_ANT_OIRAT_ULAN_ZALATA_NAME",  
		"Ulan Zalata"	),
		("LOC_UNIT_ANT_OIRAT_ULAN_ZALATA_DESCRIPTION",  
		"Oirat unique Industrial Era unit that replaces the Cavalry. Weaker but faster than the Cavalry. +10 [ICON_STRENGTH] Combat Strength vs Mounted Units. +5 [ICON_STRENGTH] Combat Strength when attacking."),
		("LOC_PEDIA_UNITS_PAGE_UNIT_ANT_OIRAT_ULAN_ZALATA_CHAPTER_HISTORY_PARA_1",  
		"Ulan Zalata literally translates in Oirat to Red-Tasselled Ones, in reference to the distinctive red tassel that hung from the headgear of the Oirat and Kalmyk riders. The tassel, introduced by Togon-Taishi in 1443, initially served to distinguish the Oirat cavalry from their Mongol neighbours, and was later incorporated by the Kalmyks as an essential part of ceremonial clothing. Oirat/Kalmky cavalry became renowned for their widespread use of lances within both Europe and Asia, and the later Uhlans of Poland and neighbouring European powers would adopt their name from the Ulan Zalata."),			
		("LOC_ABILITY_ANT_ULAN_ATTACK_BONUS_NAME",  
		"Offensive Bonus"),
		("LOC_ABILITY_ANT_ULAN_ATTACK_BONUS_DESCRIPTION",  
		"+5 [ICON_Strength] Combat Strength when attacking."),
--========================================================================================================================
-- UYANGIIN GER
--========================================================================================================================
		("LOC_IMPROVEMENT_ANT_GER_NAME",  
		"Uyangiin Ger"	),
		("LOC_IMPROVEMENT_ANT_GER_DESCRIPTION",  
		"Unlocks the Builder ability to construct an Uyangiin Ger, unique to Oirat.[NEWLINE][NEWLINE]+1 [ICON_FAITH] Faith, +1 [ICON_PRODUCTION] Production, and adjacent Holy Sites receive a standard [ICON_FAITH] Faith adjacency bonus. Additional [ICON_PRODUCTION] Production as you advance through the Civics Tree for adjacenet Pastures. +0.5 [ICON_HOUSING] Housing. Cannot be built on hills or adjacent to another Uyangiin Ger."),
		("LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_ANT_GER_CHAPTER_HISTORY_PARA_1",  
		"A Ger, or Yurt, is a portable, round tent covered with skins or felt and was commonly used as a dwelling by nomads across the whole of the Central Asian steppe. After adopting the Buddhist religion, the Oirats constructed and maintained many monasteries, and incorporated them into their Yurts to create a mobile monastery. They maintained tent monasteries throughout present-day eastern Kazakhstan and along the migratory route they took across southern Siberia to the Volga. They also maintained tent monasteries around Lake Issyk Kul in present-day Kyrgyzstan. The yurts that incorporated artistic styles and symbolism of the Buddhist monasteries became known in Mongolian as Uyangiin Ger, literally meaning home of lyrics or home of melodies."),
		("LOC_DISTRICT_ANT_UYANGIIN_GER_FAITH",  
		"+{1_num} [ICON_Faith] Faith from the adjacent {1_Num : plural 1?Uyangiin Ger; other?Uyangiin Gers;}."),		
--========================================================================================================================
-- ERDENIIN GALDAN
--========================================================================================================================
		("LOC_LEADER_ANT_GALDAN_NAME",  
		"Galdan"	),
--------------------------------------------------------------------
-- LUA
--------------------------------------------------------------------
		("LOC_TRAIT_LEADER_ANT_BOSHUGTU_KHAN_NAME",  
		"Boshigt Khan"	),
		("LOC_TRAIT_LEADER_ANT_BOSHUGTU_KHAN_DESCRIPTION",  
		"Combat victories provide [ICON_FAITH] Faith equal to 50% of the [ICON_STRENGTH] Combat Strength of the defeated unit. May purchase Light and Heavy Cavalry units with [ICON_FAITH] Faith. After founding a religion, a free Missionary appears in the [ICON_CAPITAL] Capital each time you conquer a new city."), 
--------------------------------------------------------------------
-- Agenda
--------------------------------------------------------------------
		("LOC_AGENDA_ANT_SUBJUGATION_OF_KHALKHA_NAME",  
		"Subjugation of Khalkha"	),
		("LOC_AGENDA_ANT_SUBJUGATION_OF_KHALKHA_DESCRIPTION",  
		"Aims to bring all followers of his religion under his sway. Dislikes civilizations of the same religion that are not his declared friend, significantly more so if they share his continent. Likes civilizations of the same religion that are his declared friend."	),

		("LOC_DIPLO_KUDO_LEADER_ANT_GALDAN_REASON_ANY",  
		"(You are his declared friend and share the same religion.)"	),
		("LOC_DIPLO_MODIFIER_ANT_SUBJUGATION_OF_KHALKHA_SAME_RELIGION_FRIEND",  
		"Galdan is pleased you are building a relationship based on your common faith."	),

		("LOC_DIPLO_WARNING_LEADER_ANT_GALDAN_REASON_ANY",  
		"(You share his religion, but will not declare friendship.)"	),
		("LOC_DIPLO_MODIFIER_ANT_SUBJUGATION_OF_KHALKHA_SAME_RELIGION_NOT_FRIEND",  
		"Galdan detests the fact you will not declare friendship with your religious brothers."	),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_1",
		"As fourth son of Erdeni Batur, founder of the Dzungar Khanate, Galdan was a descendant of Esen Taishi, the powerful Oirat Khan of the Northern Yuan dynasty who united the western Mongols in the 15th century."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_2",
		"Galdan's mother Yum Aga was a daughter of Güshi Khan, the first Khoshut-Oirat King of Tibet. At age of 7, Galdan was sent to Lhasa to be educated as a lama under the 5th Dalai Lama at Tashilhunpo Monastery. When Galdan's mother Amin-Dara arrived to Lhasa to inform Galdan of Sengge's death, Galdan immediately renounced his status as a lama and quickly returned to the Irtysh Valley to avenge him."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_3",
		"Galdan took his widow Anu-Dara, granddaughter of Ochirtu, as his bride. Conflict within the family soon erupted again when Ochirtu, fearing Galdan's popularity, supported Galdan's uncle and rival Choqur Ubashi. In 1678 Galdan forced Ochirtu to flee to Kokonur and established hegemony over the Oirats."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_4",
		"The inhabitants of Yarkant appealed to Galdan Khan for help. The Dzungars conquered Kashgar and Yarkant and Galdan had its ruler chosen by its inhabitants. In order to cement this union, Galdan attempted to ally with Zasaghtu Khan Shira who lost part of his subjects to Tushiyetu Khan Chakhundorji, and moved his orda near the Altai Mountains."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_5",
		"Galdan dispatched troops under his younger brother Dorji-jav against the Tushiyetu Khan the next year, but they were eventually defeated and Dorji-jav was killed in the ensuing battle. Chakhundorji murdered Degdeehei Mergen Ahai of the Zasaghtu Khan who was on the way to Galdan. To avenge the death of his brother and expand his influence over other Mongol areas, Galdan prepared for war with the Khalkha of eastern Mongolia."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_6",
		"Galdan established a friendly relationship with the Russians who were at war with Tushiyetu Khan over territories near Lake Baikal in northern Khalkha. Bonded by a common interest in defeating the Khalkha, both Galdan and the Russians simultaneously attacked and conquered most of the territories of Khalkha."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_7",
		"Armed with superior firearms provided by the Russians, Galdan attacked the land of the late Zasaghtu Khan, and advanced to the dominion of Tushiyetu Khan. The Qing court strengthened its northern border garrisons, and advised the Khalkhas to resist Galdan."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_8",
		"By his victory in 1688, Galdan had driven the Khalkhas into the arms of the Qing and made himself a military threat to the Manchus. Galdan's troops were seriously defeated by the Khalkha troops supported by the Qing army and Galdan retreated back to Khalkha."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_9",
		"Kangxi's plan was to personally lead an army northwest to Galdan while sending a second army north from the Ordos Desert to block his escape. Kangxi reached the Kherlen, found Galdan gone, but was forced to turn back due to lack of supplies. On 12 June 1696, the same day Kangxi turned back, Galdan blundered into the western army and was disastrously defeated at Terelj's Zuunmod near the upper Tuul River east of Ulan Bator."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_HISTORY_PARA_10",
		"A son and a daughter of Galdan remained in Tsewang Araptan's household along with a lama wanted by the Kangxi Emperor for desertion and for assisting Galdan. The 5th Dalai Lama was actually dead at the time, but the regent issued orders in his name, which were from the Dalai Lama, so far as Galdan knew."),
--------------------------------------------------------------------
-- Diplo
--------------------------------------------------------------------
		("LOC_LOADING_INFO_LEADER_ANT_GALDAN",  
		"Watch how the plains stretch across the horizon, Galdan. Lands ripe for conquest surround you from every direction. It falls to you to show the world the immense power of the hordes of Oirat. Take your steed and sword, and prove yourself a truly unstopable force - a Divine Khan."  	),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_ANT_GALDAN_ANY",                                      
		"Foolish."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_ANT_GALDAN_ANY",                                      
		"You make wise choices, friend."),
		("LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_ANT_GALDAN_ANY",                                     
		"The cooporation of the Oirat tribes is the source of our power. Let us cooperate as well, and reap the benefits."),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                     
		"Friendship? I focus my time on more important things. Conquest, mostly."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                     
		"A friendship Oirat can truly benefit from. I accept."),
		("LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_ANT_GALDAN_ANY",                                      
		"Nomads such as myself thrive off conquest and war! If you didn't already realise that, you will soon enough. Prepare yourself."),
		("LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                     
		"Hmh. If it is war you desire, so be it. Just don't come begging for mercy once my tribesmen plunder your greatest cities."),
		("LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                      
		"You have defeated a Khan. A divine Khan. Maybe my great conquests will live on through you."),
		("LOC_DIPLO_DEFEAT_FROM_AI_LEADER_ANT_GALDAN_ANY",                                     
		"You have defeated a Khan. A divine Khan. Maybe my great conquests will live on through you."),
		("LOC_DIPLO_DELEGATION_FROM_AI_LEADER_ANT_GALDAN_ANY",                                     
		"We're not short of livestock here in Dzungaria. My delegation travels your way with a host of local meats for you to sample."),
		("LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                     
		"I do not wish to see you delegation tread on these soils."),
		("LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                     
		"Your delegation has been guided peacefully to the capital, and gratefully received."),
		("LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_ANT_GALDAN_ANY",                                     
		"You are a disgrace to your people, and to yourself. (Denounces You)"),
		("LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                      
		"It's only natural that a minnow such as yourself would try to belittle me with words. True power lies in the sword, you know?"),
		("LOC_DIPLO_FIRST_MEET_LEADER_ANT_GALDAN_ANY",                                     
		"Greetings, you stand in the presence of Galdan Boshigt Khan. I represent my people, the Oirat, as well as all the true followers of my faith. Whom do you represent?"),
		("LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_ANT_GALDAN_ANY",                                     
		"While majority of my people choose not to settle down in cities, there does happen to be one settlement nearby. Why not visit it yourself?"),
		("LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_ANT_GALDAN_ANY",                                     
		"Of course."),
		("LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_ANT_GALDAN_ANY",                                     
		"Share with me the knowledge of your capital, and I shall share mine."),
		("LOC_DIPLO_GREETING_LEADER_ANT_GALDAN_ANY",                                     
		"Hello."),
		("LOC_DIPLO_WARNING_EXIT_LEADER_ANT_GALDAN_ANY",                                     
		"The title of Divine Khan was bestowed upon me by the Dalai Lama himself. If you cannot respect that, then you are no true follower of this faith."),
		("LOC_DIPLO_KUDO_EXIT_LEADER_ANT_GALDAN_ANY",                                      
		"You embrace our common faith, and as such the Divine Khan shall embrace you."),
		("LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_ANT_GALDAN_ANY",                                      
		"Let us strike up a powerful alliance."),
		("LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_ANT_GALDAN_ANY",                                     
		"{LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_ANT_GALDAN_ANY}"),
		("LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_ANT_GALDAN_ANY",                                     
		"{LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_ANT_GALDAN_ANY}"),
		("LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_ANT_GALDAN_ANY",                                      
		"We shall agree to peace, temporarily."),
		("LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_ANT_GALDAN_ANY",                                      
		"I still have much business to settle, the war must continue."),
		("LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_ANT_GALDAN_ANY",                                     
		"I seldom favor peace. In this instance, however, it is in my interest to pursue it."),
		("LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                     
		"Of course, these lands are always open to you and yours."),
		("LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_ANT_GALDAN_ANY",                                     
		"My people know not to let you or your armies anywhere near our territory."),
		("LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_ANT_GALDAN_ANY",                                     
		"An urge to traverse the lands runs through the blood of my people. Kindly allow us passage through your borders."),
		("LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_ANT_GALDAN_ANY",                                      
		"Hah, that's quite the army you have on my borders! Remove them at once, unless you wish to face an even greater force."),
--------------------------------------------------------------------
-- Quote and Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_ANT_GALDAN_QUOTE",  
		"A tree may be strong, but will bend under the weight of its fruits."),
		("LOC_PEDIA_LEADERS_PAGE_ANT_GALDAN_TITLE",
		"Choros Erdeniin Galdan"),
		("LOC_PEDIA_LEADERS_PAGE_ANT_GALDAN_SUBTITLE",
		"Divine Khan"),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_CAPSULE_BODY",
		"Under the guidance of their Divine Khan, the Oirat can become an unstoppable cavalry force through an effective combination of religious and militaristic bonuses."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_ANT_GALDAN_CHAPTER_DETAILED_BODY",
		"With Galdan at the helm, the Oirat can build on the religious bonuses provided by their early unique improvement, the Uyangiin Ger. Producing an early builder would be a priority for anyone playing Galdan, as it will allow them to construct a tile improvement generating both [ICON_FAITH] Faith and [ICON_PRODUCTION] Production early on. Chase after Barbarians to generate additional faith to push yourself into an early pantheon and possibly patronise Great People. As you continue to expand your [ICON_FAITH] Faith output through the game, this can be supplemented with Galdan's ability to purchase Cavalry units with faith, allowing the Oirat to maintain a sizable horse-based army without having to invest as much production into their military. Conquering cities will grant missionaries to assist in spreading religion, while constructing Holy Sites and religious buildings will generate greater amounts of faith to purchase cavalry with, allowing Galdan to pursue either a militarily-assisted Religious victory or a religiously-assisted Domination victory, among other options.");
--------------------------------------------------------------------
--------------------------------------------------------------------